"
Copyright 2000-2015  Alan Knight

GLORP is made available to use under the Smalltalk Shared-Base license, as detailed below.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement.  In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.

The Software shall not restrict in any way the license of any software or product that includes it or makes use of it in any way, subject to the following conditions.

If you modify the class definitions or the methods of the Software, the following requirement will apply to the source code of those modified class definitions and modified methods only.  It will not apply to the definitions or methods of subclasses of classes in the Software, or to code that calls the Software and/or has the Software call back to it, through using classes and methods of the software in code, or by using blocks, or by using the #perform: mechanism or similar mechanisms, or any other code, modified or otherwise, that is not a class definition of a class provided by the Software, or a method provided by the Software.  If modifications to the classes or methods of the Software are included in software or products made available under any license then the source code of those modifications shall on request be made available to the originating supplier of the Software, who shall provide them to anyone on request under this license.

The above copyright notice and license terms shall be included in all copies of the Software or of substantial portions of the Software.

The intent of this license is not to change the meaning of the prior license but to provide a self-contained and clear license that imposes the intended conditions. The previous license referenced another license but had negations and redefinitions of its conditions, and became particularly confusing as that license changed in subsequent versions.
"
Class {
	#name : #GlorpLicense,
	#superclass : #Object,
	#category : 'Glorp-Core'
}

{ #category : #license }
GlorpLicense class >> LICENSE [
"Copyright 2000-2015  Alan Knight

GLORP is made available to use under the Smalltalk Shared-Base license, as detailed below.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions.

The Software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement.  In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.

The Software shall not restrict in any way the license of any software or product that includes it or makes use of it in any way, subject to the following conditions.

If you modify the class definitions or the methods of the Software, the following requirement will apply to the source code of those modified class definitions and modified methods only.  It will not apply to the definitions or methods of subclasses of classes in the Software, or to code that calls the Software and/or has the Software call back to it, through using classes and methods of the software in code, or by using blocks, or by using the #perform: mechanism or similar mechanisms, or any other code, modified or otherwise, that is not a class definition of a class provided by the Software, or a method provided by the Software.  If modifications to the classes or methods of the Software are included in software or products made available under any license then the source code of those modifications shall on request be made available to the originating supplier of the Software, who shall provide them to anyone on request under this license.

The above copyright notice and license terms shall be included in all copies of the Software or of substantial portions of the Software.

The intent of this license is not to change the meaning of the prior license but to provide a self-contained and clear license that imposes the intended conditions. The previous license referenced another license but had negations and redefinitions of its conditions, and became particularly confusing as that license changed in subsequent versions."
]
