Class {
	#name : #GlorpTinyPublisher,
	#superclass : #Object,
	#instVars : [
		'id',
		'name',
		'titles',
		'titlesWithNumberInStock'
	],
	#category : 'Glorp-Tests-Models'
}

{ #category : #accessing }
GlorpTinyPublisher >> id [

	^id
]

{ #category : #accessing }
GlorpTinyPublisher >> id: anObject [

	id := anObject
]

{ #category : #accessing }
GlorpTinyPublisher >> name [

	^name
]

{ #category : #accessing }
GlorpTinyPublisher >> name: anObject [

	name := anObject
]

{ #category : #accessing }
GlorpTinyPublisher >> titles [

	^titles
]

{ #category : #accessing }
GlorpTinyPublisher >> titles: anObject [

	titles := anObject
]

{ #category : #accessing }
GlorpTinyPublisher >> titlesWithNumberInStock [

	^titlesWithNumberInStock
]

{ #category : #accessing }
GlorpTinyPublisher >> titlesWithNumberInStock: anObject [

	titlesWithNumberInStock := anObject
]
