"
A publisher employee in the Encyclopedia mode
"
Class {
	#name : #GlorpPublisherEmployee,
	#superclass : #Object,
	#instVars : [
		'id',
		'name',
		'jobTitle'
	],
	#category : #'Glorp-Unit-Tests-Models - Encyclopedia'
}

{ #category : #accessing }
GlorpPublisherEmployee >> id [

	^ id
]

{ #category : #accessing }
GlorpPublisherEmployee >> id: anObject [

	id := anObject
]

{ #category : #accessing }
GlorpPublisherEmployee >> jobTitle [

	^ jobTitle
]

{ #category : #accessing }
GlorpPublisherEmployee >> jobTitle: aString [

	jobTitle := aString
]

{ #category : #accessing }
GlorpPublisherEmployee >> name [

	^ name
]

{ #category : #accessing }
GlorpPublisherEmployee >> name: anObject [

	name := anObject
]
